version: '3.8'
services:
  api-server:
    restart: always
    image: 0x8861/mernstack-api-server:latest
    env_file: .env.prod
    environment:
      - NODE_ENV=production # Override the NODE_ENV in .env file

  client:
    restart: always
    image: 0x8861/mernstack-client:latest
    environment:
      - TZ
    depends_on:
      - api-server

  nginx-proxy:
    restart: always
    image: 0x8861/mernstack-nginx-proxy:latest
    volumes:
      - /mern-stack/ssl:/etc/nginx/ssl
    ports:
      - '80:80'
      - '443:443'
    environment:
      - LETSENCRYPT
      - LE_EMAIL
      - LE_FQDN
      - PLACEHOLDER_1=${SERVER_PORT}
      - PLACEHOLDER_2=${PUBLIC_IP_ADDRESS}
      - TZ
    depends_on:
      - api-server
      - client
