version: '3.8'
services:
  mongo: # Remove this if you use external MongoDB service such as MongoDB Atlas
    restart: always
    image: mongo:latest

  api-server:
    restart: always
    build:
      context: ./
      dockerfile: ./server/Dockerfile.prod
    env_file: .env.staging
    environment:
      - NODE_ENV=staging # Override the NODE_ENV in .env.staging file
      - MONGO_URI=mongodb://mongo/merndb # Remove this if you use external MongoDB service such as MongoDB Atlas
    depends_on:
      - mongo

  client:
    restart: always
    build:
      context: ./
      dockerfile: ./client/Dockerfile.prod
      args:
        - facebook_app_id=${FACEBOOK_APP_ID}
        - google_client_id=${GOOGLE_CLIENT_ID}
    environment:
      - PORT
    depends_on:
      - api-server

  nginx-proxy:
    restart: always
    build:
      context: ./
      dockerfile: ./nginx-proxy/Dockerfile.staging
    ports:
      - '${NGINX_PROXY_PORT}:${NGINX_PROXY_PORT}'
    environment:
      - NGINX_PROXY_PORT
      - NODE_ENV
      - PORT
      - SERVER_PORT
    depends_on:
      - api-server
      - client
