version: '3.8'
services:
  mongo: # Remove this if you use external MongoDB service such as MongoDB Atlas
    restart: always
    image: mongo:latest

  api-server:
    restart: always
    build:
      context: ./
      dockerfile: ./server/Dockerfile.prod
    env_file: .env.prod
    environment:
      - NODE_ENV=production # Override the NODE_ENV in .env file
      - MONGO_URI=mongodb://mongo/merndb # Remove this if you use external MongoDB service such as MongoDB Atlas
    depends_on:
      - mongo

  client:
    restart: always
    build:
      context: ./
      dockerfile: ./client/Dockerfile.prod
      args:
        - facebook_app_id=${FACEBOOK_APP_ID}
        - google_client_id=${GOOGLE_CLIENT_ID}
    environment:
      - TZ
    depends_on:
      - api-server

  nginx-proxy:
    restart: always
    build:
      context: ./
      dockerfile: ./nginx-proxy/Dockerfile.prod
    volumes:
      - /mern-stack/ssl:/etc/nginx/ssl
    ports:
      - '80:80'
      - '443:443'
    environment:
      - LETSENCRYPT
      - LE_EMAIL
      - LE_FQDN
      - PLACEHOLDER_1=${SERVER_PORT}
      - PLACEHOLDER_2=${PUBLIC_IP_ADDRESS}
      - TZ
    depends_on:
      - api-server
      - client
