version: '3.8'
services:
  mongo:
    image: mongo:latest
  server-api:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - /mern-stack/server/node_modules
      - ./server:/mern-stack/server
    environment:
      MONGO_URI: mongodb://mongo/merndb
    ports:
      - '8080:8080'
    depends_on:
      - mongo
